version: '3.7'
services:
  database:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nesty
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
